language: python
python:
  - "2.7"
install: "pip install -r requirements-test.txt --allow-external mysql-connector-python && pip install -e ."
before_script:
  - mysql -e 'create database royal_test_example;'
script:  "python setup.py nosetests"
services:
  - mongodb
after_success:
    - coveralls