language: python
python: "3.6"
services:
  - mongodb

env:
  matrix:
    - TOXENV=py27-all
  install:
    - pip install tox

before_script:
  - mysql -e 'create database royal_test_example;'
script:
  - tox
after_success:
  - coveralls
